import { createElement } from '@lwc/engine-dom';
import TimesheetPortalCalendarView from 'c/timesheetPortalCalendarView';


describe('c-timesheet-portal-calendar-view', () => {
    afterEach(() => {
       
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-timesheet-portal-calendar-view', {
            is: TimesheetPortalCalendarView
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});